CREATE TABLE eventos
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(255) NOT NULL,
    descricao        TEXT,
    identificador    VARCHAR(100) NOT NULL UNIQUE,
    data_hora_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    data_hora_fim    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    local_evento     VARCHAR(255),
    capacidade       INTEGER NOT NULL CHECK (capacidade > 0),
    organizador      VARCHAR(255),
    tipo             VARCHAR(50),
    CONSTRAINT pk_eventos PRIMARY KEY (id)
);